.\" Copyright (c) 2005 Johannes Zellner
.TH XFCE4-TASKMANAGER "1" "September 2005" "xfce4-taskmanager 0.4.0" "User Commands"
.SH NAME
xfce4-taskmanager \- a task (system process) manager for Xfce.
.SH SYNOPSIS
.B xfce4-taskmanager
.SH DESCRIPTION
.PP
xfce4-taskmanager is a GUI task (system process) manager for Xfce Desktop.
Environment. .
.SH COPYRIGHT
Copyright \(co 2005 Johannes Zellner
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

